# 'bundle exec jekyll serve'

# Site settings
name: BrainKO
email: ayin1989dy@gamil.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://brainko.top"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules